services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ~/ollama:/root/.ollama
    networks:
      - net

  app:
    image: amithkoujalgi/pdf-bot:1.0.0
    ports:
      - 8000:8000
    environment:
      - OLLAMA_API_BASE_URL=http://127.0.0.1:11434
      - MODEL=llama3.2:1b
    networks:
      - net

networks:
  net: